import sqlite3

conn = sqlite3.connect('project.db')

conn.execute("DROP TABLE IF EXISTS USER")

conn.execute('''
CREATE TABLE USER(
    ID INTEGER PRIMARY KEY,
    GENDER INTEGER NOT NULL,
    FIRSTNAME TEXT NOT NULL,
    LASTNAME TEXT NOT NULL,
    YEAR INTEGER NOT NULL,
    MONTH INTEGER NOT NULL,
    DAY INTEGER NOT NULL,
    EMAIL TEXT NOT NULL,
    PASSWORD TEXT NOT NULL
    );''')

conn.close()